### ISSUE TITLE
Support IE10+

### ISSUE THREAD

**Issue by IdemIsDito** [jeroenoomsNL/the-flex-grid#2]
http://jeroenoomsnl.github.io/the-flex-grid/ say's the grid is supported by IE10+.  
It does'nt work in IE10 and IE11. So, I was wondering. Is it a typo or do I need to have some polyfills?

**Comment by PizzaPete** [comment]
Hey @IdemIsDito,

Did you use the the-flex-grid.prefixed.css version? That one has prefixes for IE and should work (http://caniuse.com/#search=flexbox).
