### ISSUE TITLE
Using something like colspan

### ISSUE THREAD

**Issue by eL-Prova** [jeroenoomsNL/the-flex-grid#3]
@jeroenoomsNL Thx for your grid system.
Your examples are good and your CSS clean so credits for that 👍 

I have only one problem.
I want to make a grid like the nested grid.
However I have a column of 6, and want 2 columns of 12 nested in a 6 column

So you will get something like:
[column-6] [column-6 [column-12][column-12]]

By adding an row-equal I was hoping the column is growing correctly. But it dont seems to be.
So do you have a small example how I can achive this?

**Comment by jeroenoomsNL** [comment]
Hi! Thank you for using this project.
I'll check this later today and I'll let you know!

**Comment by jeroenoomsNL** [comment]
Hi! Thanks for mentioning this because there was a bug in the nested grids with equal heights. I fixed this and released a new version (v1.5.0). 

On the demo page I've added an example how to use it:
http://jeroenoomsnl.github.io/the-flex-grid/#nested-grid-equal-height

**Comment by eL-Prova** [comment]
@jeroenoomsNL version 1.5 is not available at release tab ;-)

**Comment by jeroenoomsNL** [comment]
@eL-Prova sorry! I forgot to push the tag. But is was already available on NPM.
