### ISSUE TITLE
max-width: 960px, why?

### ISSUE THREAD

**Issue by brunocascio** [jeroenoomsNL/the-flex-grid#4]
Hi!

I'm wondering about the `min-width` property on .grid class at line (https://github.com/jeroenoomsNL/the-flex-grid/blob/master/dist/the-flex-grid.css#L8).

Is it okay?

**Comment by jeroenoomsNL** [comment]
Hi! I removed this one for now, you are right! It's released in version 1.5.1.
I'm working on a SCSS version as well, with silent classes. Then it will be possible to configure the max-width when it's needed.
