### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by eL-Prova** [jeroenoomsNL/the-flex-grid#8]
Hi Jeroen,

Can you make a extension to your css so rows will fill the space when the grid is nested?
Use case:

Grid contains 2 columns.
Column 1 contains nested grid
-- Nested grid contains 2 rows with a column
Column 2 has 100vh
The nested grid has just 50vh of the screen

I should expect that rows of the nested grid will fill the space by its parent
Result will be grid with 2 columns of 100vh and nested grid space of 50vh per row

**Comment by jeroenoomsNL** [comment]
Thanks for you suggestion and I agree that this might be useful, so I implemented this today. I hope you like it! 

http://jeroenoomsnl.github.io/the-flex-grid/#nested-grid-with-full-grid-height
