### ISSUE TITLE
Bug row-reverse when responsive columns are used

### ISSUE THREAD

**Issue by eL-Prova** [jeroenoomsNL/the-flex-grid#9]
I got the following code:

```CSS
<div class="row row-reverse">
    <div class="col-large-6 col-small-12">
        <div class="content">1</div>
    </div>
    <div class="col-large-6 col-small-12">
        <div class="content">2</div>
    </div>
</div>
```

The row-reverse adds the CSS styling `flex-direction:row-reverse;` however when the columns are small (12) flex will put the columns under each other and results in no reverse. Changing to column-reverse works correct.

I expect when col is over full width, it should not set `flex-direction` to `row-reverse` but to `column-reverse`

**Comment by jeroenoomsNL** [comment]
Column-reverse won't do the trick, because we never know when the container is wrapping. But I found another solution. It seems to be possible to use flex-wrap: wrap-reverse; for that case. I will update it in a couple of minutes.
